import {FilterType} from '../../../filter/models/filter-type';
import {PredicateTreeMetadata} from './generator-metadata';

/**
 * Saved filter generated by the {@link AbstractAdvancedSearchComponent}.
 */
export interface FilterMetadata {
    filterType: FilterType;
    predicateMetadata: PredicateTreeMetadata;
    /**
     * Serialized {@link Category} classes, that were available in the saved search component.
     */
    searchCategories: Array<string>;
}
